<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>WebSocket</title>
	<link href="https://cdn.bootcss.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.bootcss.com/jquery/1.12.3/jquery.js"></script>
<script type="text/javascript">

	$(function(){
		var ws = new WebSocket("ws://116.62.58.170:9502");
		if(ws.readyState!=1){
    		ws.onopen = function() {
        		var info = JSON.stringify({type:'connect',member_id:<?php echo Yaf\Session::getInstance()->get('member_id');?>,nickname:'<?php echo Yaf\Session::getInstance()->get('nickname');?>'});
    			ws.send(info);
    		};
		}
		$("#send").click(function(){
			var fd = $(".active").attr("data-id");
			var message = $("#message").val();
			ws.send(JSON.stringify({fd:fd,message:message,type:'chat'}));
		});
		
		ws.onmessage = function(evt) {
			var received =  eval("(" + evt.data + ")"); 
			switch(received.type){
				case "connect":
					$("#fd").val(received.fd);
					break; 
				case "chat":
					var html = '<div style="padding:10px 5px;border-bottom:1px solid #f2f2f2;">'+received.nickname+'&nbsp;&nbsp;'+received.time+'<br>'+received.message+'</div>';
					$(".record_hid").after(html);
					break;
				default:
					$(".list-group").empty();
					var html = '';
					$(received).each(function(index) {
			    		var val = received[index];
						html+= '<li class="list-group-item" data-id="'+val.fd+'">'+val.nickname+'&nbsp;&nbsp;<span class="label label-success">在线</span></li>'
					});
					$(".list-group").append(html);
					break;
			}
// 			if(received.type=='connect'){
// 				$("#fd").val(received_msg.fd);
// 			}else {
// 				alert(received_msg);
// 			}
		};
	});

$(function(){
	$("body").on("click",".list-group-item",function(){
		var _this = $(this);
		$(".list-group-item").removeClass("active");
		_this.addClass("active");
	});
});
</script>
<style type="text/css">
.container{
	margin-top: 20px;
}
.col{
	border: 1px solid #f2f2f2;
	padding: 10px;
}
.list-group-item{
	cursor: pointer;
}
.active{
	border: 1px solid green;
    margin-bottom: 0px;
}
</style>
</head>
<body>
<div class="container">
	<div id="sse">
		<!--<input type="text" class="msg" value="">
		<button id="send">发送</button>
		-->

	</div>
	<div class="row">
	  <h2>WEB聊天系统</h2>
      <div class="col-xs-4 col">
      	<ul class="list-group">
      	 
        </ul>
      </div>
      <div class="col-xs-6 col record">
      	<div class="record_hid"></div>
      </div>
      <div class="col-xs-10 col">
      	<textarea class="form-control" id="message" rows="3"></textarea><br>
      	<input type="hidden" id="fd" name="fa" value="">
      	<button type="button" class="btn btn-success" id="send">发送</button>
      </div>
    </div>
</div>
</body>
</html>