<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link href="https://cdn.bootcss.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
<!-- 	<script src="https://cdn.bootcss.com/bootstrap/3.1.0/js/bootstrap.min.js"></script> -->
</head>
<body>
	<div style="width:40%;margin:0px auto;margin-top: 10%;border: 1px solid #f2f2f2;padding-top: 40px;padding-right: 20px;border-radius: 5px;">
    <form class="form-horizontal" method="post" action="?type=login">
      <div class="form-group">
        <label for="mobile" class="col-sm-2 control-label">手机号</label>
        <div class="col-sm-10">
          <input type="text" name="mobile" class="form-control" id="mobile" placeholder="请输入手机号">
        </div>
      </div>
      <div class="form-group">
        <label for="password" class="col-sm-2 control-label">密码</label>
        <div class="col-sm-10">
          <input type="password" name="password" class="form-control" id="password" placeholder="请输入密码">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">登录</button>
        </div>
      </div>
    </form>
    </div>
</body>
</html>